name: Trigger auto deployment for container-app-657z6hsysi4lo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-657z6hsysi4lo-AutoDeployTrigger-2f1c6c1e-7cf2-4722-94b1-54554c8a21fe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP657Z6HSYSI4LO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP657Z6HSYSI4LO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP657Z6HSYSI4LO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry657z6hsysi4lo.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP657Z6HSYSI4LO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP657Z6HSYSI4LO_REGISTRY_PASSWORD }}
          containerAppName: container-app-657z6hsysi4lo
          resourceGroup: msdocspythonflaskwebappquickstartbc1e
          imageToBuild: containerregistry657z6hsysi4lo.azurecr.io/container-app-657z6hsysi4lo:${{ github.sha }}
          


